### ISSUE TITLE
Review fight and kill experience in multitarget attacks

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#30]
1) Decide and comment for each multitarget ability what should happen with experience
2) Test each ability and make sure it works that way

Re https://github.com/inferno8/wesnoth-Era_of_Magic/issues/29#issuecomment-900631828

**Comment by ProditorMagnus** [comment]
Points to answer, when

**Attacker damages third party**

1. Damager gets fight xp?
2. Damager gets kill xp?
3. Third party gets fight xp?

**Defender damages third party, for abilities where it can happen**

4. Damager gets fight xp?
5. Damager gets kill xp?
6. Third party gets fight xp?

**Exceptions**

7. Some abilities do not inflict damage to third party while defending. Some do. In case it should differ based on ability, describe which ones.
8. Any other exceptions?

**Comment by ProditorMagnus** [comment]
Goal of this task is to simplify multitarget damage logic and reduce code duplication to cover use cases for
- all around
- beam
- cleave
- dragon breath
- triple strike

It would also provide place for unified handling for interaction with **awake** in case it is desired.

**Comment by ProditorMagnus** [comment]
Added reminder to fix it during next ageless release if the issue is still happening.

**Comment by ProditorMagnus** [comment]
Started with first in list, guru. Test confirms xp is not given. https://github.com/inferno8/wesnoth-Era_of_Magic/commit/567bda970cbd0756ad0b053d49aa701af82c7714 https://i.vgy.me/bR43JB.png

**Comment by ProditorMagnus** [comment]
@inferno8 WEAPON_SPECIAL_EOMA_AREAEFFECTRANDOM and WEAPON_SPECIAL_EOMA_AREAEFFECT both have id=eoma_areaeffect_event, so one of them never works. However, in addition to that I see WEAPON_SPECIAL_EOMA_AREAEFFECTRANDOM is supposed to damage every time attacker hits, while WEAPON_SPECIAL_EOMA_AREAEFFECT is supposed to damage every time chance is rolled over value, no matter if main attack hits or misses.

In the Guru note you said
> should be replaced with “random area effect” (see below) with a chance to hit set to 100% (that way all adjacent units are affected = no randomness).  
Should WEAPON_SPECIAL_EOMA_AREAEFFECTRANDOM be changed to not work with misses? Or allow it as buff to guru?

**Comment by inferno8** [comment]
@ProditorMagnus  Let's allow it as a buff to Guru. 

WEAPON_SPECIAL_EOMA_AREAEFFECT is marked for removal, so once it is gone, the 'same event id in use' issue should no longer be a problem in this case.

**Comment by ProditorMagnus** [comment]
Beam had unique issue where every hit gave xp to both attacker and defender. Solved that, and then results are
```
$ run_all_tests()
fail EoMa_Guru attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Guru attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Guru attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Guru attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Great_Efreeti attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Great_Efreeti attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Great_Efreeti attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Great_Efreeti attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Omen attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Omen attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Omen attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Omen attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Chaos_Rider attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Chaos_Rider attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Chaos_Rider attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Chaos_Rider attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Chaos_Hydra attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Chaos_Hydra attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Chaos_Hydra attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Chaos_Hydra attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Mechanical_Dragon attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Mechanical_Dragon attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Mechanical_Dragon attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Mechanical_Dragon attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Kirios attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Kirios attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Kirios attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Kirios attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Kirios attacker xp if cfg.defender_dies and cfg.thirdparty_dies expected 48 but was 24
pass EoMa_Kirios attacker xp if cfg.defender_dies and not cfg.thirdparty_dies is 24
pass thirdparty xp if cfg.defender_dies and not cfg.thirdparty_dies is 3
fail EoMa_Kirios attacker xp if not cfg.defender_dies and cfg.thirdparty_dies expected 27 but was 3
pass defender xp if not cfg.defender_dies and cfg.thirdparty_dies is 3
pass EoMa_Kirios attacker xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass defender xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3
pass thirdparty xp if not cfg.defender_dies and not cfg.thirdparty_dies is 3

```

**Comment by ProditorMagnus** [comment]
Underlying issue was that storing units for xp considerations was done after they were already dead.

**Comment by ProditorMagnus** [comment]
```
        name= _ "awaken"
        description=_"If a friendly adjacent unit with more than one hitpoint dies, it is resurrected, gets +6 experience and remains in battle with one hitpoint. If it dies again (having one hitpoint), it will be killed for sure.
Doesn't work on units attacked indirectly e.g. by area weapons."
```
Was "on units attacked indirectly" just for easier coding or also for balance? Since I already work with pain absorber started thinking of awaken too.

**Comment by inferno8** [comment]
> Was "on units attacked indirectly" just for easier coding or also for balance?

Balance. Having it working on units attacked indirectly would make Inspired (unit) too powerful imo. That's why I introduced this limitation. Changing this behavior would probably require rebalancing the unit from scratch. I will consult IPS on that matter, but for now I would keep this limitation as it is for now.

**Comment by ProditorMagnus** [comment]
Getting concerned why cleave is the only one disabled in rpg when triplestrikes is almost the same.

**Comment by inferno8** [comment]
> Getting concerned why cleave is the only one disabled in rpg when triplestrikes is almost the same.

Well, I just briefly discussed this with IPS and here's the conclusion: "_Regarding cleave if you hit a unit that is at very low defense (20%) you have more chances harming other secondary target instead of directly attacking that unit._" That was probably the main reason why it was disabled in RPG. I believe the decision was made more than a year ago, so I don't remember all the details.

If you know how to combine these two specials into one or have some other ideas, I am all ears.

**Comment by ProditorMagnus** [comment]
Cleave has 50% chance to hit, no matter what main target chance is. I would add rpg condition to all the area specials I focused on during this task.

**Comment by inferno8** [comment]
> I would add rpg condition to all the area specials I focused on during this task.

Ok. Go ahead.
