### ISSUE TITLE
Harbinger's chaotic vortex leads to a lua error

### ISSUE THREAD

**Issue by loreb** [inferno8/wesnoth-Era_of_Magic#31]
Minor issue, tested using the latest release with wesnoth 1.16.6

Use the chaotic vortex, everything looks ok, when the faction with the unit that was just hit gets its turn there's an error saying that `set_variable_local` expected a string but got a boolean
(screenshot at https://imgur.com/a/ZQJ2fT7, I don't know how to copy&paste that out of wesnoth)

**Comment by inferno8** [comment]
The bug has been confirmed on 1.16.8 and it will be fixed in the next EoMa release. Thank you for reporting!
