### ISSUE TITLE
Unit type and base unit type events are merged

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-Era_of_Magic#44]
~~Too many unbalanced tags corrupts other abilities. I also don't think the ``{OPTIONS}`` trick even works.~~

For example, TLU's ability Meditation main event handler is garbled and never run.

![imagen](https://user-images.githubusercontent.com/4925744/227000420-9f33e2cf-32ab-4518-b43e-b31a7a8f3665.png)

**Comment by ProditorMagnus** [comment]
What makes you consider it garbled?

**Comment by Slayer95** [comment]
> What makes you consider it garbled?

In absense of eoma_summon, the event handler for "Meditate" looks like this:

![imagen](https://user-images.githubusercontent.com/4925744/227016914-f35dda0a-66d5-430d-95aa-f15a385159c8.png)

As can be seen in the first few scenarios of TLU, when Mehir is a Lvl 2 unit unable to summon.

**Comment by ProditorMagnus** [comment]
This requires further investigation. Most likely cause from this image would be [+event], but neither of these addons has that.

**Comment by Slayer95** [comment]
Kamikaze Drone (EoMa_Drone_kamikaze inherits from EoMa_Drone) was, as far as I coud tell, the only candidate for being similarly bugged. But on a fast check, I see no evidence of it being the case, and -contrarywise- I do see why it might be working properly.

Unless there is other evidence (from e.g. @ProditorMagnus 's WMLTreeTools validation), I believe this issue can be closed.

**Comment by ProditorMagnus** [comment]
My validation does not confirm in game issues, it is just static analyzing so since EoMa_Drone_kamikaze has both [event] and [base_unit] it would be flagged as concern.

**Comment by ProditorMagnus** [comment]
Confirmed in game that events are merged https://i.vgy.me/Seom3n.png

**Comment by ProditorMagnus** [comment]
Now that https://github.com/wesnoth/wesnoth/issues/3827 is basically confirmed to be same case as this issue creating link between tasks.

**Comment by Slayer95** [comment]
> Confirmed in game that events are merged https://i.vgy.me/Seom3n.png

Addressed by https://github.com/inferno8/wesnoth-To_Lands_Unknown/pull/41

(On afterthought, that wasn't an issue of the Era itself.)

**Comment by ProditorMagnus** [comment]
Unit type can have events, but it cant be inherited and have events on both levels.

**Comment by Slayer95** [comment]
Closing in absence of new repros.
