### ISSUE TITLE
Enable summon on mixed terrain Wwf

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#55]
I would expect to be able to summon on ford https://i.vgy.me/CpVbVm.png

**Comment by ProditorMagnus** [comment]
Even if not for all summons, as flying, jinn should use same filter as air elemental ` EXCEPT_ON=_off^_usr,Q*,*^X*,X*,*^V*`

**Comment by inferno8** [comment]
Very well. I approve all these ideas.
