### ISSUE TITLE
Awe immunity as undrainable

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#60]
@inferno8 @ReynBolt what you think of additionally having undrainable status give immune to awe? Magical race is already immune so there should be little if any changes in EoMa units.

**Comment by inferno8** [comment]
This makes sense, I guess. 
The vast majority (if not all) of undrainable units fall under undead, mechanical and magical categories and all these groups are incapable of felling fear.
AWE_FILTER mentions them as well as Tharis, Cyclops and fearless units in general. (awe.cfg:85). Having Awe immunity as undrainable would probably greatly simplify this filter, so I am ok with this change.
