### ISSUE TITLE
Visualize kamikaze range differently from melee

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#61]
I think Era_of_Magic_Resources\images\icons\profiles/kamikaze_attack.png should not look same as melee. Solution with my art skills would be to make it red.

**Comment by inferno8** [comment]
The convention for range icons is to use B&W images, iirc. What about a new icon showing an arrow pointing to an explosion? Pretty self-explanatory in my opinion. Here's an exmaple:
![eoma-kamikaze-icon-ingame](https://github.com/inferno8/wesnoth-Era_of_Magic/assets/35965303/bc038fb9-b613-4128-8ee9-c1b49b052814)
![eoma-kamikaze-icon-big](https://github.com/inferno8/wesnoth-Era_of_Magic/assets/35965303/50844493-6244-463e-9108-78a6ab17dd6b)
![kamikaze_attack](https://github.com/inferno8/wesnoth-Era_of_Magic/assets/35965303/4c65223f-b881-473f-894b-18ca9635d5fa)

**Comment by ProditorMagnus** [comment]
Looks good.
