### ISSUE TITLE
Improve swift strike code

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#62]
```
+#define WEAPON_SPECIAL_AE_MAG_SWIFTSTRIKE VALUE
+    [attacks]
+        id=AE_mag_swiftstrike
+        name= _ "swift strike"+" +"+{VALUE}
+        description= _ "When this attack is used offensively, the attacker gets +1 bonus strike."
+        apply_to=self
+        active_on=offense
+        add=1
+    [/attacks]
+#enddef
```
If it takes {VALUE}, then value should affect function of the ability. I also dont see why this should be forbidden in rpg.

Also noticed FROZEN_REGENERATION looks like it does not work on mixed terrain like ice+forest.

**Comment by inferno8** [comment]
Hmm, I was pretty sure I put {VALUE} there... And that Frozen Regeneration issue needs to be fixed as well. Thanks for reporting!

I'll try to fix these two once I am back from my little wesbreak. You can fix them too, if you want. We are all volunteers here anyway. 😉

**Comment by ProditorMagnus** [comment]
When it is only used for 1 anyways, then for ease of translations it might be easier to just remove the parameter.

**Comment by inferno8** [comment]
Good point. We can always re-add VALUE later, if such need arises. For now we can do without it as you suggested.
