### ISSUE TITLE
Triple strike lua error on 1.17.22

### ISSUE THREAD

**Issue by inferno8** [inferno8/wesnoth-Era_of_Magic#65]
When killing third party with triple strike, the following lua error appears on 1.17.22 (-d  --log-debug=wml):
![2023-11-04 130916](https://github.com/inferno8/wesnoth-Era_of_Magic/assets/35965303/6e6186c5-5986-4d8b-a132-c792b715f7e8)

Context: Raging Hydra attacked one of two Bronze Warriors. The primary target's HP was initially full, while the other unit had only 1HP (debug). When the bystander was successfully killed, the lua error appeared. This also happens during defense and in TLU.

The error does not appear on 1.16.x.

On the other hand, the similar "All around" weapon special works fine.

I am not a lua expert but it looks like [harm_unit] tries to access a non-existing unit in an array at the given index. 
@ProditorMagnus Any ideas on how to fix this?

**Comment by ProditorMagnus** [comment]
In general to investigate such issues I add breakpoints between wml actions in order to find which specific tag triggers it. Downloading 1.17.22.

**Comment by ProditorMagnus** [comment]
modificationUnitTest confirms the issue, that makes it easier.

**Comment by ProditorMagnus** [comment]
No need to change anything here, will be solved by https://github.com/wesnoth/wesnoth/issues/8019

**Comment by inferno8** [comment]
Ok, thanks!
