### ISSUE TITLE
awake ability edge case

### ISSUE THREAD

**Issue by andrzejskutela** [inferno8/wesnoth-Era_of_Magic#69]
Hello,

Awake ability does not revive neighbouring units if they are killed by kamikaze attack. My presumption here is that because kamikaze attack removes the attacker on attack_end event ([kill] fire_events=yes), so then on die event awake ability runs [filter_second_attack] which fails because second_unit does not exist any more at this stage. Because this filter_second_attack fails the awake revival is never triggered.

**Comment by ProditorMagnus** [comment]
Would be good to get @inferno8 decision whether to document or fix this interaction.

**Comment by inferno8** [comment]
For now the **easiest solution** would be to document that interaction. All kamikaze attacks in EoMa are close proximity explosions that often vaporize targets leaving almost nothing to revive. But on the other hand there are many even more powerful attacks in EoMa that turn units into piles of ash (Summons Master's incantation of power, for example). Making exception for kamikaze would lead to inconsistency. So the **best solution** is to fix this interaction at some point, imo.
