### ISSUE TITLE
Unknown unit types

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#8]
Tested on 1.13.14, log has
Unknown unit type : EoMa_Dwarvish_Arctic_Scout
Unknown unit type : EoMa_Dwarvish_Arctic_Commando

**Comment by ProditorMagnus** [comment]
Grep shows it exists in translations file.

**Comment by inferno8** [comment]
Fixed for 3.1.2
