### ISSUE TITLE
Unknown unit types in the final scenario

### ISSUE THREAD

**Issue by Xel** [inferno8/wesnoth-Era_of_Magic#9]
Hey.. I'm posting here cause there's no repo for To Lands Unknown. Sorry if it's the wrong place
Had an error for unknown unit types in the final scenario 
I'm playing 1.14.0-2, To Lands unknown 3.0.0. Please find attached a screenshot

![screenshot from 2018-05-04 04-40-23](https://user-images.githubusercontent.com/886449/39613702-b256f114-4f58-11e8-9c5f-d43eca9d463f.png)

**Comment by inferno8** [comment]
It looks like there is a minor typo in one of unit ids inside that scenario. This issue will be fixed in the next version of the campaign. Thank you for reporting 😉
